export const darkTheme = {
  color: {
    defaultFontColor: "#9a93ab",
    blackTransparent: "rgba(0, 0, 0, 0.7)",
    primaryColor: "#6423FF",
    lightPrimaryColor: "#CF5FE4",
    lighterPrimaryColor: "#ec9bfc",
    secondColor: "#25293E",
    darknestWhite: "#FFFFFA",
    white: "#FFFFFF",
    background: "#0d0e1d",
    cardBackground: "black",
    tag: "#dedede",
    homeIcon: "#ec9bfc",
    toggleIcon: "#6423FF",
    borderToggleIcon: "#ec9bfc",
  },
  breakpoint: {
    extraSmall: "350px",
    xs: "420px",
    another: "768px",
    s: "991px",
    m: "1300px",
  },
  darkTheme: {
    background: "#101223",
    defaultFontColor: "#a899cd",
    secondFontColor: "#fefefe",
    primaryColor: "#6423ff",
    lightPrimaryColor: "#cf5fe4",
    lighterPrimaryColor: "#ec9bfc",
    secondColor: "#25293E",
    white: "#FFFFFF",
  },
};
